### ISSUE TITLE
Single UID column in JSON template is unsupported

### ISSUE THREAD

**Issue by cutright** [IQDM/IQDM-Analytics#14]
When creating a custom template, multiple UID columns are required, otherwise IQDMA crashes.

```
/Users/ninja/PycharmProjects/IQDM-Analytics/iqdma/stats.py:156: RuntimeWarning: All-NaN slice encountered
  data = getattr(np, f"nan{func}")(self.data, 1)
ERROR: Unhandled exception: Traceback (most recent call last):
  File "/Users/ninja/PycharmProjects/IQDM-Analytics/iqdma/main.py", line 733, in on_table_select
    self.update_chart_data(index)
  File "/Users/ninja/PycharmProjects/IQDM-Analytics/iqdma/main.py", line 752, in update_chart_data
    for v in self.report_data.uid_data
  File "/Users/ninja/PycharmProjects/IQDM-Analytics/iqdma/main.py", line 752, in <listcomp>
    for v in self.report_data.uid_data
IndexError: list index out of range
```

https://github.com/IQDM/IQDM-Analytics/blob/df91efc0699d611b99ebc4bea89fb9eeabc270e9/iqdma/main.py#L747-L754

**Comment by cutright** [comment]
Fixed: 30e831662e57416404f14e1112085b7a0a5fe73d
